### ISSUE TITLE
Error unknown option: default-path

### ISSUE THREAD

**Issue by wikimatze** [jimeh/tmuxifier#28]
Hio Jim,

thanks for this awesome plugin, I really enjoy and appreciate what you did because it is doing exactly the things which I missed by using tmuxinator.

Here is the reason for the error https://github.com/tmuxinator/tmuxinator/issues/170.

I have the following session file:

``` bash
if initialize_session "testt"; then
  load_window "padrino-book"
  load_window "job-vacancy"

  select_window 1
fi

finalize_and_go_to_session
```

and here is the contents of the two window layouts:

`padrino-book`

``` bash
window_root "$HOME/Dropbox/padrino/manuscript"
new_window "section"
run_cmd "vim 02-04-user-profile.md"     # runs in active pane

window_root "$HOME/Dropbox/notes"
new_window "notes"
run_cmd "vim padrino.txt"

window_root "$HOME/Dropbox/notes"
new_window "todo"
run_cmd "vim padrino-todo.txt"

new_window "irc"
run_cmd "irssi"
```

`job-vacancy`:

``` bash
window_root "~/git-repositories/job-vacancy"
new_window "job-vacancy"

run_cmd "vim"

split_v 20
run_cmd "bundle exec padrino s"
split_h 80
run_cmd "bundle exec rspec spec"

select_pane 1
```

Even when I turn of the `window_root` settings in each of my window layouts, I'm getting this error message. The strange thing is, that my window setup described above is working fine. 

Maybe you can add some tmux 1.8 and 1.90 deprecation warning in your script so that no other users of your plugin get the impression that something is broken.

Best regards from Berlin.

**Comment by nathantech2005** [comment]
You guys need to spell out the command so I don't have to guess or look up 10 docs to find it. How does -c even come close to meaning path? set-option default-path was working fine for me. Then it just stopped. I did not change my tmux version. Also neww is a terrible command. And tmux 2.3 is telling me neww is not a valid command. I am basically stuck having to manually set everything. none of my config commands are working. I really want to use this project and possibly even contribute. But we've got to start at the basics. Follow standard linux command naming conventions.
