### ISSUE TITLE
Not show cmd?

### ISSUE THREAD

**Issue by starmatt** [jimeh/tmuxifier#54]
Hello, when run_cmd works, in there a way to not make the command appear in the terminal?

**Comment by jimeh** [comment]
Do you mean prevent the output of the command from being printed in the console, or completely hiding the fact that the command was run?

If it's to prevent output, just add ` &> /dev/null` to the end of your command. 

If you wanna hide the command completely so it doesn't appear in a terminal, just run it within the window/session layout file. The layout files are just regular bash scripts with some custom helper commands available for working with tmuxifier.

Im closing this issue, as it's more of a general question than an issue report, but please feel free to reply if you have any further questions :)
