### ISSUE TITLE
TPM Support

### ISSUE THREAD

**Issue by snowe2010** [jimeh/tmuxifier#82]
Is there any way to add TPM support to Tmuxifier? The instructions for how to do so are here, https://github.com/tmux-plugins/tpm/blob/master/docs/how_to_create_plugin.md. It seems that you just need to add a `*.tmux` file.

**Comment by 0inp** [comment]
https://github.com/jimeh/tmuxifier/pull/88

@snowe2010 @jimeh

**Comment by snowe2010** [comment]
Wow is that all it takes? Thought for sure it would need more than that. Well thank you 👍🏼

**Comment by jimeh** [comment]
#88 is now merged, thanks @0inp ❤️.

And damn, sorry @snowe2010. How has **FIVE** years passed since this issue was opened? Feels like it was last month or something I saw this and was thinking I need to look into TPM 😅

**Comment by snowe2010** [comment]
haha 🤷🏼 I don't even remember making this issue 😂 

I have several projects like that as well lol. I'm like. Oof, did I leave that ticket for that long???

**Comment by 0inp** [comment]
Thanks a lot to both of you ! This is my first PR and contribution to open source project ! That's not a lot, but I feel kind of proud ahah ^^
